server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/day03
    username: root
    password: yi123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true #当遇到同样的名字的时候，是否允许覆盖
mybatis:
  type-aliases-package: cn.ly.userservice.pojo

eureka:
  client:
    service-url:
          defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 20  # 最长保留时间如果超过20秒没有发送心跳，
    lease-renewal-interval-in-seconds:  10 #每10秒续约注册中心，每个10秒服务会向注册中心发送一次心跳，证明自己还活着
    instance-id: ${spring.application.name}:${server.port}