server:
  port: 10086 # 端口
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
eureka:
  client:
    register-with-eureka: false # 是否注册自己作为eureka服务,默认为true
    fetch-registry: false    # 是否拉取其它服务的信息，默认是true
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
  server:
    eviction-interval-timer-in-ms: 5000 #每个5秒驱逐一次失效服务
    enable-self-preservation: false
