server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false #\u4E0D\u628A\u81EA\u5DF1\u4F5C\u4E3A\u670D\u52A1\u5668\u6CE8\u518C
    fetch-registry: false #\u4E0D\u62C9\u53BB\u670D\u52A1\u5217\u8868
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 5000 #每个5秒驱逐一次失效服务
    enable-self-preservation: false
